### ISSUE TITLE
unable to compile without kdelibs(?) devel environment

### ISSUE THREAD

**Issue by pvanek** [zballina/lxqt-config-randr#1]
[ 39%] Building CXX object src/CMakeFiles/razorxrandr.dir/randr.cpp.o  
In file included from /home/pvanek/oss/razor/razorxrandr/src/randr.cpp:22:0:  
/home/pvanek/oss/razor/razorxrandr/src/randr.h:41:21: fatal error: fixx11h.h: No such file or directory
compilation terminated.

**Comment by zballina** [comment]
Fix error, view issue #3
