### ISSUE TITLE
Crash when used in Virtualbox.

### ISSUE THREAD

**Issue by PCMan** [zballina/lxqt-config-randr#4]
[pcman@localhost build]$  ./src/lxqt-config-randr 
1 4 "X Resize and Rotate extension version 1.4" 
Using XRANDR extension 1.3 or greater. 
XRANDR error base:  147 
0x19ab5f0 
Creating CRTC object for XID 0 ("None") 
Creating CRTC object for XID 62 
Querying information about CRTC 62 
Creating output object for XID 63 
XID 63 is output "VBOX0" (connected) 
Setting CRTC 62 (enabled) on output "VBOX0" 
Possible CRTCs for output "VBOX0" : 
- CRTC 62 
  Current configuration for output "VBOX0" : 
- Refresh rate: 59.9998 
- Rect: QRect(0,0 1280x720) 
- Rotation: 1 
  legacy 1 
  Display is valid 
  HAS_RANDR_1_3 
  Before create Scene 
  Segmentation fault (core dump)

The line that crashed is in randrconfig.cpp.
m_scene = new QGraphicsScene(m_display->currentScreen()->rect(), screenView);

After some tracing, I noted that m_display->currentScreen() returns NULL in some cases. In this case, currentLegacyScreen() is provided.
Please see randrdisplay.cpp, line 86.
# ifdef HAS_RANDR_1_2

```
// check if we have more than one output, if no, revert to the legacy behavior
if (RandR::has_1_2)
{
    int count = 0;
    foreach(RandRScreen *screen, m_screens)
        count += screen->outputs().count();

    if (count < 2)
    {
        RandR::has_1_2 = false;
        for (int i = 0; i < m_numScreens; ++i)
        {
            delete m_screens[i];
            m_legacyScreens.append(new LegacyRandRScreen(i));
        }
        m_screens.clear();
    }
}
```
# endif

This piece of code delete the screen object, and create legacy screen objects instead if count < 2. In this case, m_display->currentScreen() will be NULL. So screen->rect() crashes.
Unfortunately, LegacyScreen and Screen seem to be different things and cannot be used interchangeably. So LayoutManager may not work with it.
Any clues how to fix it?

**Comment by zballina** [comment]
Thanks for reporting, it was a mistake that in the latest update. Active a # ifdef should not. 'll Check again to see but something happened to me again.
